/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

export function getArchiveChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'dwsp-archive-change',
    description: '在实验工作流中归档已完成的变更。适用于实现完成后进行收尾归档。',
    instructions: `在实验工作流中归档已完成变更。

**输入**: 可选传入变更名。若未传入，请根据对话上下文判断；若信息含糊，必须提示用户从可用变更中选择。

**步骤**

1. **若未提供变更名，提示用户选择**

   运行 \`dwsp list --json\` 获取可用变更，并使用 **AskUserQuestion tool** 让用户选择。

   仅展示活跃变更（未归档）。
   若可用，展示每个变更对应的 schema。

   **重要**: 不要猜测或自动替用户决定，始终让用户自行选择。

2. **检查产物完成状态**

   运行 \`dwsp status --change "<name>" --json\` 检查产物完成情况。

   解析 JSON 以了解：
   - \`schemaName\`: 当前使用的工作流
   - \`artifacts\`: 各产物及其状态（\`done\` 或其他）

   **若存在非 \`done\` 的产物：**
   - 展示未完成产物的警告
   - 使用 **AskUserQuestion tool** 询问是否继续
   - 用户确认后再继续

3. **检查任务完成状态**

   读取任务文件（通常是 \`tasks.md\`），检查未完成任务。

   统计 \`- [ ]\`（未完成）与 \`- [x]\`（已完成）的数量。

   **若发现未完成任务：**
   - 展示未完成任务数量的警告
   - 使用 **AskUserQuestion tool** 询问是否继续
   - 用户确认后再继续

   **若不存在任务文件：** 直接继续，不做任务警告。

4. **评估增量规格同步状态**

   检查 \`duowenspec/changes/<name>/specs/\` 下是否存在增量 specs。若不存在，跳过同步提示。

   **若存在增量 specs：**
   - 将每个增量 spec 与对应主 spec（\`duowenspec/specs/<capability>/spec.md\`）进行比较
   - 判断将应用的变更类型（新增、修改、删除、重命名）
   - 在询问前先给出合并后的差异摘要

   **提示选项：**
   - 若有差异："立即同步（推荐）"、"不同步直接归档"
   - 若看起来已同步："直接归档"、"仍然同步"、"取消"

   若用户选择同步，使用 Task 工具（subagent_type: "general-purpose", prompt: "使用 Skill tool 调用 dwsp-sync-specs，同步变更 '<name>'。增量 spec 分析：<在此包含你分析后的增量摘要>"）。无论是否同步，之后都继续归档流程。

5. **执行归档**

   如果归档目录不存在，先创建：
   \`\`\`bash
   mkdir -p duowenspec/changes/archive
   \`\`\`

   使用当天日期生成目标目录名：\`YYYY-MM-DD-<change-name>\`

   **检查目标目录是否已存在：**
   - 若已存在：报错并建议重命名已有归档，或改期归档
   - 若不存在：将变更目录移动到归档目录

   \`\`\`bash
   mv duowenspec/changes/<name> duowenspec/changes/archive/YYYY-MM-DD-<name>
   \`\`\`

6. **展示摘要**

   展示归档结果摘要，包括：
   - 变更名称
   - 使用的 schema
   - 归档位置
   - 是否已同步 specs（如适用）
   - 是否存在警告（产物/任务未完成）

**成功输出**

\`\`\`
## 归档完成

**变更:** <change-name>
**工作流:** <schema-name>
**归档位置:** duowenspec/changes/archive/YYYY-MM-DD-<name>/
**规格同步:** ✓ 已同步到主 specs（或“无增量 specs”或“已跳过同步”）

全部产物完成。全部任务完成。
\`\`\`

**约束**
- 未提供变更名时，必须先让用户选择变更
- 使用产物图（\`dwsp status --json\`）检查完成状态
- 对警告不强制阻断，但必须明确告知并取得确认
- 移动目录时保留 .duowenspec.yaml（随目录一起移动）
- 始终给出清晰的归档结果摘要
- 若用户要求同步，使用 dwsp-sync-specs 的智能体驱动方式
- 若存在增量 specs，必须先完成同步评估并展示合并摘要，再询问用户`,
    license: 'MIT',
    compatibility: '需要安装 dwsp CLI。',
    metadata: { author: 'duowenspec', version: '1.0' },
  };
}

export function getOpsxArchiveCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Archive',
    description: '在实验工作流中归档已完成变更',
    category: '工作流',
    tags: ['workflow', 'archive', 'experimental'],
    content: `在实验工作流中归档已完成变更。

**输入**: 可选在 \`/dwsp:archive\` 后传入变更名（例如 \`/dwsp:archive add-auth\`）。若未传入，请根据对话上下文判断；若信息含糊，必须提示用户从可用变更中选择。

**步骤**

1. **若未提供变更名，提示用户选择**

   运行 \`dwsp list --json\` 获取可用变更，并使用 **AskUserQuestion tool** 让用户选择。

   仅展示活跃变更（未归档）。
   若可用，展示每个变更对应的 schema。

   **重要**: 不要猜测或自动替用户决定，始终让用户自行选择。

2. **检查产物完成状态**

   运行 \`dwsp status --change "<name>" --json\` 检查产物完成情况。

   解析 JSON 以了解：
   - \`schemaName\`: 当前使用的工作流
   - \`artifacts\`: 各产物及其状态（\`done\` 或其他）

   **若存在非 \`done\` 的产物：**
   - 展示未完成产物的警告
   - 提示用户确认是否继续
   - 用户确认后再继续

3. **检查任务完成状态**

   读取任务文件（通常是 \`tasks.md\`），检查未完成任务。

   统计 \`- [ ]\`（未完成）与 \`- [x]\`（已完成）的数量。

   **若发现未完成任务：**
   - 展示未完成任务数量的警告
   - 提示用户确认是否继续
   - 用户确认后再继续

   **若不存在任务文件：** 直接继续，不做任务警告。

4. **评估增量规格同步状态**

   检查 \`duowenspec/changes/<name>/specs/\` 下是否存在增量 specs。若不存在，跳过同步提示。

   **若存在增量 specs：**
   - 将每个增量 spec 与对应主 spec（\`duowenspec/specs/<capability>/spec.md\`）进行比较
   - 判断将应用的变更类型（新增、修改、删除、重命名）
   - 在询问前先给出合并后的差异摘要

   **提示选项：**
   - 若有差异："立即同步（推荐）"、"不同步直接归档"
   - 若看起来已同步："直接归档"、"仍然同步"、"取消"

   若用户选择同步，使用 Task 工具（subagent_type: "general-purpose", prompt: "使用 Skill tool 调用 dwsp-sync-specs，同步变更 '<name>'。增量 spec 分析：<在此包含你分析后的增量摘要>"）。无论是否同步，之后都继续归档流程。

5. **执行归档**

   如果归档目录不存在，先创建：
   \`\`\`bash
   mkdir -p duowenspec/changes/archive
   \`\`\`

   使用当天日期生成目标目录名：\`YYYY-MM-DD-<change-name>\`

   **检查目标目录是否已存在：**
   - 若已存在：报错并建议重命名已有归档，或改期归档
   - 若不存在：将变更目录移动到归档目录

   \`\`\`bash
   mv duowenspec/changes/<name> duowenspec/changes/archive/YYYY-MM-DD-<name>
   \`\`\`

6. **展示摘要**

   展示归档结果摘要，包括：
   - 变更名称
   - 使用的 schema
   - 归档位置
   - 规格同步状态（已同步 / 已跳过同步 / 无增量 specs）
   - 是否存在警告（产物/任务未完成）

**成功输出**

\`\`\`
## 归档完成

**变更:** <change-name>
**工作流:** <schema-name>
**归档位置:** duowenspec/changes/archive/YYYY-MM-DD-<name>/
**规格同步:** ✓ 已同步到主 specs

全部产物完成。全部任务完成。
\`\`\`

**成功输出（无增量规格）**

\`\`\`
## 归档完成

**变更:** <change-name>
**工作流:** <schema-name>
**归档位置:** duowenspec/changes/archive/YYYY-MM-DD-<name>/
**规格同步:** 无增量 specs

全部产物完成。全部任务完成。
\`\`\`

**成功输出（含警告）**

\`\`\`
## 归档完成（含警告）

**变更:** <change-name>
**工作流:** <schema-name>
**归档位置:** duowenspec/changes/archive/YYYY-MM-DD-<name>/
**规格同步:** 已跳过同步（用户选择跳过）

**警告:**
- 归档时有 2 个产物未完成
- 归档时有 3 个任务未完成
- 已跳过增量 spec 同步（用户选择跳过）

如非预期，请检查该归档目录。
\`\`\`

**错误输出（归档目录已存在）**

\`\`\`
## 归档失败

**变更:** <change-name>
**目标路径:** duowenspec/changes/archive/YYYY-MM-DD-<name>/

目标归档目录已存在。

**可选操作:**
1. 重命名已有归档目录
2. 若是重复归档可删除已有目录
3. 改期后再归档
\`\`\`

**约束**
- 未提供变更名时，必须先让用户选择变更
- 使用产物图（\`dwsp status --json\`）检查完成状态
- 对警告不强制阻断，但必须明确告知并取得确认
- 移动目录时保留 .duowenspec.yaml（随目录一起移动）
- 始终给出清晰的归档结果摘要
- 若用户要求同步，使用 Skill tool 调用 \`dwsp-sync-specs\`（智能体驱动）
- 若存在增量 specs，必须先完成同步评估并展示合并摘要，再询问用户`
  };
}
