/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

export function getBulkArchiveChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'duowenspec-bulk-archive-change',
    description: '一次归档多个已完成变更。适用于并行变更统一收尾归档。',
    instructions: getBulkArchiveInstructions(),
    license: 'MIT',
    compatibility: '需要安装 dwsp CLI。',
    metadata: { author: 'duowenspec', version: '1.0' },
  };
}

function getBulkArchiveInstructions(): string {
  return `一次性归档多个已完成的变更。

这个能力允许你批量归档 change，并在需要时通过检查真实代码库来智能处理 spec 冲突，判断哪些变更实际上已经落地。

**输入**：不需要预先传参（会提示用户选择）

**步骤**

1. **获取当前活跃变更**

   运行 \`dwsp list --json\`，拿到全部活跃 change。

   如果当前没有任何活跃 change，就告知用户并停止。

2. **提示用户选择要归档的变更**

   使用 **AskUserQuestion tool** 的多选能力，让用户选择要归档的 change：
   - 每个 change 都展示它所使用的 schema
   - 提供 “全部变更” 选项
   - 允许选择任意数量（1 个也可以，2 个及以上是更常见场景）

   **重要**：不要自动代选，必须由用户明确确认。

3. **批量校验：汇总所有已选变更的状态**

   针对每个选中的 change，收集以下信息：

   a. **产物状态**：运行 \`dwsp status --change "<name>" --json\`
      - 解析 \`schemaName\` 和 \`artifacts\`
      - 记录哪些产物已是 \`done\`，哪些还没完成

   b. **任务完成度**：读取 \`duowenspec/changes/<name>/tasks.md\`
      - 统计 \`- [ ]\`（未完成）和 \`- [x]\`（已完成）数量
      - 如果没有 tasks 文件，就标记为 “无任务文件”

   c. **Delta specs**：检查 \`duowenspec/changes/<name>/specs/\` 目录
      - 列出包含哪些 capability spec
      - 对每份 spec 提取 requirement 名称（匹配 \`### Requirement: <name>\`）

4. **识别 spec 冲突**

   构建一份 \`capability -> [changes that touch it]\` 映射：

   \`\`\`
   auth -> [change-a, change-b]  <- 冲突（2 个及以上 change 同时修改）
   api  -> [change-c]            <- 正常（只有 1 个）
   \`\`\`

   当 2 个及以上已选变更同时拥有同一 capability 的 delta spec 时，就视为冲突。

5. **以 agent 方式解决冲突**

   对每个冲突，都要进入代码库核查真实实现情况：

   a. **先读各个冲突变更的 delta spec**
      - 弄清楚每个 change 声称新增或修改了什么

   b. **在代码库里搜索实现证据**
      - 查找与这些 requirement 对应的代码、函数、文件或测试

   c. **确定解决方案**
      - 如果只有一个 change 实际已经实现 → 只同步它的 specs
      - 如果两个 change 都已经实现 → 按时间顺序应用（旧的先，新覆盖旧）
      - 如果都没实现 → 跳过该冲突对应的 spec 同步，并提醒用户

   d. **记录每个冲突的处理结论**
      - 最终采用哪个 change 的 specs
      - 如果两个都要应用，按什么顺序
      - 依据是什么（你在代码库里看到了什么）

6. **展示汇总状态表**

   用一个总表把所有 change 的情况讲清楚：

   \`\`\`
   | Change               | 产物   | 任务 | Specs   | 冲突    | 状态   |
   |----------------------|--------|------|---------|---------|--------|
   | schema-management    | 完成   | 5/5  | 2 个delta | 无      | 可归档 |
   | project-config       | 完成   | 3/3  | 1 个delta | 无      | 可归档 |
   | add-oauth            | 完成   | 4/4  | 1 个delta | auth(!) | 可归档* |
   | add-verify-skill     | 剩 1 项 | 2/5 | 无      | 无      | 警告   |
   \`\`\`

   如果存在冲突，还要把解决方案讲出来：

   \`\`\`
   * 冲突处理：
     - auth spec：将先应用 add-oauth，再应用 add-jwt（两者都已实现，按时间顺序）
   \`\`\`

   如果存在未完成 change，也要明确提示：

   \`\`\`
   警告：
   - add-verify-skill：还有 1 个未完成产物、3 个未完成任务
   \`\`\`

7. **确认批量归档操作**

   使用 **AskUserQuestion tool** 做一次统一确认：

   - 例如：\"要归档 N 个变更吗？\"
   - 可以给出这些选项：
     - \"归档全部 N 个变更\"
     - \"只归档其中已就绪的 N 个（跳过未完成的）\"
     - \"取消\"

   如果包含未完成变更，要明确说明它们会带着警告一起归档。

8. **按确认结果执行归档**

   依据前面确定好的顺序处理 change（包含冲突解决后的同步顺序）：

   a. **如果存在 delta specs，就先同步 specs**
      - 使用 duowenspec-sync-specs 的方式做智能同步
      - 遇到冲突时按已确定顺序应用
      - 记录是否同步成功

   b. **执行归档**
      \`\`\`bash
      mkdir -p duowenspec/changes/archive
      mv duowenspec/changes/<name> duowenspec/changes/archive/YYYY-MM-DD-<name>
      \`\`\`

   c. **记录每个 change 的结果**
      - 成功：归档成功
      - 失败：归档过程中出错（记录错误原因）
      - 跳过：按用户选择未归档

9. **展示最终总结**

   给出最终结果说明：

   \`\`\`
   ## 批量归档完成

   已归档 3 个变更：
   - schema-management-cli -> archive/2026-01-19-schema-management-cli/
   - project-config -> archive/2026-01-19-project-config/
   - add-oauth -> archive/2026-01-19-add-oauth/

   跳过 1 个变更：
   - add-verify-skill（用户选择不归档未完成项）

   Spec 同步总结：
   - 4 份 delta spec 已同步到主 specs
   - 共解决 1 个冲突（auth：按时间顺序依次应用）
   \`\`\`

   如果有失败项，也要单独列出：

   \`\`\`
   失败 1 个变更：
   - some-change：归档目录已存在
   \`\`\`

**冲突处理示例**

示例 1：只有一个 change 真正实现
\`\`\`
冲突：specs/auth/spec.md 被 [add-oauth, add-jwt] 同时修改

检查 add-oauth：
- Delta 新增 “OAuth Provider Integration” requirement
- 搜索代码库后，发现 src/auth/oauth.ts 已实现 OAuth 流程

检查 add-jwt：
- Delta 新增 “JWT Token Handling” requirement
- 搜索代码库后，没有发现 JWT 实现

结论：只有 add-oauth 已实现，因此只同步 add-oauth 的 specs。
\`\`\`

示例 2：两个 change 都已实现
\`\`\`
冲突：specs/api/spec.md 被 [add-rest-api, add-graphql] 同时修改

检查 add-rest-api（创建于 2026-01-10）：
- Delta 新增 “REST Endpoints” requirement
- 搜索代码库后，发现 src/api/rest.ts

检查 add-graphql（创建于 2026-01-15）：
- Delta 新增 “GraphQL Schema” requirement
- 搜索代码库后，发现 src/api/graphql.ts

结论：两个 change 都已实现。将先应用 add-rest-api 的 specs，
再应用 add-graphql 的 specs（按时间顺序，新的优先级更高）。
\`\`\`

**成功输出示例**

\`\`\`
## 批量归档完成

已归档 N 个变更：
- <change-1> -> archive/YYYY-MM-DD-<change-1>/
- <change-2> -> archive/YYYY-MM-DD-<change-2>/

Spec 同步总结：
- 已同步 N 份 delta specs
- 没有冲突（或：已解决 M 个冲突）
\`\`\`

**部分成功输出示例**

\`\`\`
## 批量归档完成（部分成功）

已归档 N 个变更：
- <change-1> -> archive/YYYY-MM-DD-<change-1>/

跳过 M 个变更：
- <change-2>（用户选择不归档未完成项）

失败 K 个变更：
- <change-3>：归档目录已存在
\`\`\`

**没有可归档变更时的输出**

\`\`\`
## 没有可归档的变更

当前没有活跃 change。请先创建新的 change。
\`\`\`

**约束**
- 允许选择任意数量的 change（1 个也可以，2 个及以上更常见）
- 必须让用户手动选择，不能自动代选
- 要尽早识别 spec 冲突，并通过检查代码库来解决
- 如果两个 change 都已实现，按时间顺序应用 specs
- 只有在缺少实现证据时才跳过 spec 同步，并明确提醒用户
- 确认前必须把每个 change 的状态讲清楚
- 整批操作只做一次统一确认
- 要完整记录并汇报成功 / 跳过 / 失败的结果
- 移动到 archive 时要保留 .duowenspec.yaml
- 归档目录名使用当天日期：YYYY-MM-DD-<name>
- 如果目标归档目录已存在，该 change 记为失败，但继续处理其它 change`;
}

export function getOpsxBulkArchiveCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Bulk Archive',
    description: '一次归档多个已完成变更',
    category: '工作流',
    tags: ['workflow', 'archive', 'experimental', 'bulk'],
    content: getBulkArchiveInstructions(),
  };
}
