/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate } from '../types.js';

export function getFeedbackSkillTemplate(): SkillTemplate {
  return {
    name: 'feedback',
    description: '收集并提交关于 DuowenSpec 的用户反馈，附带上下文补充与匿名化处理。',
    instructions: `帮助用户提交关于 DuowenSpec 的反馈。

**目标**：在保护隐私的前提下，引导用户收集、补充并提交反馈内容。

**流程**

1. **从对话里收集上下文**
   - 回看最近的对话内容，理解背景
   - 识别用户当时在做什么任务
   - 记录哪些地方顺利，哪些地方不顺利
   - 抓出具体的阻塞点、摩擦点或正向反馈

2. **起草一版更完整的反馈**
   - 先写一个清晰、具体的标题（单句即可，不需要 "Feedback:" 前缀）
   - 再写正文，至少包含：
     - 用户原本想做什么
     - 实际发生了什么（好或坏都可以）
     - 与此相关的对话背景
     - 具体建议、期望或诉求

3. **匿名化敏感信息**
   - 把文件路径替换成 \`<path>\` 或更泛化的描述
   - 把 API key、token、secret 等替换成 \`<redacted>\`
   - 把公司或组织名替换成 \`<company>\`
   - 把个人姓名替换成 \`<user>\`
   - 非公开或无关的具体 URL 替换成 \`<url>\`
   - 但要保留有助于理解问题的技术细节

4. **把草稿给用户确认**
   - 把完整草稿展示给用户
   - 标题和正文都要清楚展示
   - 在提交前必须明确征得用户同意
   - 如果用户想改，就继续调整

5. **在用户确认后提交**
   - 使用 \`dwsp feedback\` 命令提交
   - 格式：\`dwsp feedback "title" --body "body content"\`
   - 命令会自动附加版本、平台、时间戳等元信息

**示例草稿**

\`\`\`
Title: Error handling in artifact workflow needs improvement

Body:
I was working on creating a new change and encountered an issue with
the artifact workflow. When I tried to continue after creating the
proposal, the system didn't clearly indicate that I needed to complete
the specs first.

Suggestion: Add clearer error messages that explain dependency chains
in the artifact workflow. Something like "Cannot create design.md
because specs are not complete (0/2 done)."

Context: Using the spec-driven schema with <path>/my-project
\`\`\`

**匿名化示例**

Before:
\`\`\`
Working on /Users/john/mycompany/auth-service/src/oauth.ts
Failed with API key: sk_live_abc123xyz
Working at Acme Corp
\`\`\`

After:
\`\`\`
Working on <path>/oauth.ts
Failed with API key: <redacted>
Working at <company>
\`\`\`

**约束**

- 提交前必须展示完整草稿
- 提交前必须明确征得用户同意
- 必须先做好敏感信息匿名化
- 允许用户在提交前继续修改草稿
- 未经确认不得直接提交
- 需要保留与问题相关的技术上下文
- 可以保留对当前对话有价值的具体观察

**用户确认是必需步骤**

始终这样询问：
\`\`\`
这是我起草的反馈：

Title: [title]

Body:
[body]

你看这样是否合适？如果你想改，我可以继续调整；也可以直接按这版提交。
\`\`\`

只有在用户明确确认后，才继续提交。`,
    license: 'MIT',
    compatibility: '需要安装 dwsp CLI。',
    metadata: { author: 'duowenspec', version: '1.0' },
  };
}
