/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';
import { getModoBEndImplementationHint } from './shared-b-end.js';

export function getFfChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-ff-change',
    description: '快速完成 OpenSpec 产物生成。适用于用户想一次性生成实现所需全部产物，而不逐步推进。',
    instructions: `用“快速推进”方式一次生成开始实现所需的全部产物。

**输入**：用户的请求应当包含一个变更名（kebab-case），或者描述想要构建/修复的内容。

**步骤**

1. **如果输入还不够清晰，先问清楚要做什么**

   使用 **AskUserQuestion tool**（开放式提问，不给预设选项）询问：
   > "你想处理什么变更？请描述你想新增或修复的内容。"

   根据用户描述推导一个 kebab-case 名称（例如："新增用户认证" → \`add-user-auth\`）。

   **重要**：在没弄清用户目标前，不要继续。

2. **创建变更目录**
   \`\`\`bash
   openspec new change "<name>"
   \`\`\`
   这会在 \`openspec/changes/<name>/\` 下创建变更骨架。

3. **获取产物构建顺序**
   \`\`\`bash
   openspec status --change "<name>" --json
   \`\`\`
   解析返回的 JSON，重点看：
   - \`applyRequires\`：开始实现前必须完成的产物 ID（例如 \`["tasks"]\`）
   - \`artifacts\`：全部产物的状态及依赖关系

4. **按顺序持续创建产物，直到满足 apply 前置条件**

   使用 **TodoWrite tool** 跟踪产物创建进度。

   按依赖顺序循环处理产物（优先处理没有未完成依赖的产物）。

   a. **针对每个 \`ready\` 状态的产物（依赖已满足）**：
      - 获取指令：
        \`\`\`bash
        openspec instructions <artifact-id> --change "<name>" --json
        \`\`\`
      - 返回的 JSON 中重点字段有：
        - \`context\`：项目背景（给你的约束，不要直接输出）
        - \`rules\`：产物规则（给你的约束，不要直接输出）
        - \`template\`：产物文件应使用的结构
        - \`instruction\`：该产物类型的写作指导
        - \`outputPath\`：应当写入的位置
        - \`dependencies\`：可供参考的已完成产物
      - 先阅读已完成的依赖产物，获取上下文
      - 以 \`template\` 为结构创建产物文件
      - 写作时遵守 \`context\` 与 \`rules\`，但不要把它们原文复制进文件
      - 简短反馈进度："✓ 已创建 <artifact-id>"

   b. **持续处理，直到 \`applyRequires\` 中的产物全部完成**
      - 每创建完一份产物，都重新运行 \`openspec status --change "<name>" --json\`
      - 检查 \`applyRequires\` 中每个产物在 \`artifacts\` 里是否都已是 \`status: "done"\`
      - 全部完成后停止

   c. **如果某份产物需要额外用户输入**（上下文仍不够明确）：
      - 使用 **AskUserQuestion tool** 继续澄清
      - 然后继续创建

5. **展示最终状态**
   \`\`\`bash
   openspec status --change "<name>"
   \`\`\`

**输出**

全部产物创建完成后，给出一段总结：
- 变更名称与所在路径
- 本次创建了哪些产物，并简要说明
- 当前是否已经可以进入实现："所有产物已创建完成，可以开始实现。"
- 提示："运行 \`/dwsp:apply\`，或者直接让我开始实现这些任务。"

**产物创建指引**

- 每类产物都以 \`openspec instructions\` 返回的 \`instruction\` 为准
- schema 已经定义了每份产物该写什么，按它来
- 创建新产物前先阅读依赖产物
- 以 \`template\` 作为输出结构，把对应章节补完整
- **重要**：\`context\` 与 \`rules\` 是给你的约束，不是产物正文
  - 不要把 \`<context>\`、\`<rules>\`、\`<project_context>\` 这些块复制进产物
  - 它们只用于指导你写作，不应出现在最终文件中

**约束**
- 要把开始实现前所需的全部产物都创建完成（即 schema 的 \`apply.requires\`）
- 创建新产物前一定先读依赖产物
- 如果上下文确实关键且不清楚，可以问用户；但在大多数情况下应做合理判断，保持推进节奏
- 如果同名变更已存在，建议继续已有变更，而不是重复创建
- 每写完一份产物，都要确认文件已经落盘，再进入下一份

${getModoBEndImplementationHint()}`,
    license: 'MIT',
    compatibility: '需要安装 openspec CLI。',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxFfCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Fast Forward',
    description: '一步创建变更并生成实现所需全部产物',
    category: '工作流',
    tags: ['workflow', 'artifacts', 'experimental'],
    content: `用“快速推进”方式一次生成开始实现所需的全部产物。

**输入**：\`/dwsp:ff\` 后面的参数可以是变更名（kebab-case），也可以是用户想构建内容的描述。

**步骤**

1. **如果还没有输入内容，先问清楚要做什么**

   使用 **AskUserQuestion tool**（开放式提问，不给预设选项）询问：
   > "你想处理什么变更？请描述你想新增或修复的内容。"

   根据用户描述推导一个 kebab-case 名称（例如："新增用户认证" → \`add-user-auth\`）。

   **重要**：在没弄清用户目标前，不要继续。

2. **创建变更目录**
   \`\`\`bash
   openspec new change "<name>"
   \`\`\`
   这会在 \`openspec/changes/<name>/\` 下创建变更骨架。

3. **获取产物构建顺序**
   \`\`\`bash
   openspec status --change "<name>" --json
   \`\`\`
   解析返回的 JSON，重点看：
   - \`applyRequires\`：开始实现前必须完成的产物 ID（例如 \`["tasks"]\`）
   - \`artifacts\`：全部产物的状态及依赖关系

4. **按顺序持续创建产物，直到满足 apply 前置条件**

   使用 **TodoWrite tool** 跟踪产物创建进度。

   按依赖顺序循环处理产物（优先处理没有未完成依赖的产物）。

   a. **针对每个 \`ready\` 状态的产物（依赖已满足）**：
      - 获取指令：
        \`\`\`bash
        openspec instructions <artifact-id> --change "<name>" --json
        \`\`\`
      - 返回的 JSON 中重点字段有：
        - \`context\`：项目背景（给你的约束，不要直接输出）
        - \`rules\`：产物规则（给你的约束，不要直接输出）
        - \`template\`：产物文件应使用的结构
        - \`instruction\`：该产物类型的写作指导
        - \`outputPath\`：应当写入的位置
        - \`dependencies\`：可供参考的已完成产物
      - 先阅读已完成的依赖产物，获取上下文
      - 以 \`template\` 为结构创建产物文件
      - 写作时遵守 \`context\` 与 \`rules\`，但不要把它们原文复制进文件
      - 简短反馈进度："✓ 已创建 <artifact-id>"

   b. **持续处理，直到 \`applyRequires\` 中的产物全部完成**
      - 每创建完一份产物，都重新运行 \`openspec status --change "<name>" --json\`
      - 检查 \`applyRequires\` 中每个产物在 \`artifacts\` 里是否都已是 \`status: "done"\`
      - 全部完成后停止

   c. **如果某份产物需要额外用户输入**（上下文仍不够明确）：
      - 使用 **AskUserQuestion tool** 继续澄清
      - 然后继续创建

5. **展示最终状态**
   \`\`\`bash
   openspec status --change "<name>"
   \`\`\`

**输出**

全部产物创建完成后，给出一段总结：
- 变更名称与所在路径
- 本次创建了哪些产物，并简要说明
- 当前是否已经可以进入实现："所有产物已创建完成，可以开始实现。"
- 提示："运行 \`/dwsp:apply\` 开始实现。"

**产物创建指引**

- 每类产物都以 \`openspec instructions\` 返回的 \`instruction\` 为准
- schema 已经定义了每份产物该写什么，按它来
- 创建新产物前先阅读依赖产物
- 以 \`template\` 作为输出结构，把对应章节补完整
- **重要**：\`context\` 与 \`rules\` 是给你的约束，不是产物正文
  - 不要把 \`<context>\`、\`<rules>\`、\`<project_context>\` 这些块复制进产物
  - 它们只用于指导你写作，不应出现在最终文件中

**约束**
- 要把开始实现前所需的全部产物都创建完成（即 schema 的 \`apply.requires\`）
- 创建新产物前一定先读依赖产物
- 如果上下文确实关键且不清楚，可以问用户；但在大多数情况下应做合理判断，保持推进节奏
- 如果同名变更已存在，先问用户是继续已有变更还是重新创建
- 每写完一份产物，都要确认文件已经落盘，再进入下一份

${getModoBEndImplementationHint()}`
  };
}
