/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';
import { getModoBEndPlanningHint } from './shared-b-end.js';

export function getNewChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'duowenspec-new-change',
    description: '使用实验产物工作流发起新的 DuowenSpec 变更。适用于按步骤创建功能、修复或修改。',
    instructions: `使用实验产物驱动方式发起一个新变更。

**输入**：用户的请求应当包含一个变更名（kebab-case），或者描述想要构建/修复的内容。

**步骤**

1. **如果输入还不够清晰，先问清楚要做什么**

   使用 **AskUserQuestion tool**（开放式提问，不给预设选项）询问：
   > "你想处理什么变更？请描述你想新增或修复的内容。"

   根据用户描述推导一个 kebab-case 名称（例如："新增用户认证" → \`add-user-auth\`）。

   **重要**：在没弄清用户目标前，不要继续。

2. **确定要使用的工作流 schema**

   除非用户明确要求其它工作流，否则使用默认 schema（不要传 \`--schema\`）。

   **只有在这些情况下才使用其它 schema：**
   - 用户点名某个 schema → 传入 \`--schema <name>\`
   - 用户说“看看有哪些工作流 / schema” → 运行 \`dwsp schemas --json\` 后再让用户选择

   **否则**：直接省略 \`--schema\`，走默认流程。

3. **创建变更目录**
   \`\`\`bash
   dwsp new change "<name>"
   \`\`\`
   只有当用户明确指定非默认工作流时才追加 \`--schema <name>\`。
   这会在 \`duowenspec/changes/<name>/\` 下创建带对应 schema 的变更骨架。

4. **查看产物状态**
   \`\`\`bash
   dwsp status --change "<name>"
   \`\`\`
   这会显示哪些产物还未创建，哪些产物已经就绪（依赖满足）。

5. **获取第一份产物的指令**
   第一份产物取决于 schema（例如 spec-driven 通常先写 \`proposal\`）。
   从状态输出中找到第一个状态为 "ready" 的产物。
   \`\`\`bash
   dwsp instructions <first-artifact-id> --change "<name>"
   \`\`\`
   该命令会输出创建第一份产物所需的模板与上下文。

6. **到这里先停下，等待用户下一步指示**

**输出**

完成上述步骤后，给出一段总结：
- 变更名称与所在路径
- 当前使用的 schema / 工作流，以及它的产物顺序
- 当前状态（0/N 个产物已完成）
- 第一份产物的模板
- 提示："准备好创建第一份产物了吗？直接告诉我这次变更主要是做什么，我就可以帮你起草；或者你也可以让我继续。"

**约束**
- 现在不要创建任何产物，只展示指令
- 不要继续推进到第一份产物模板之后的阶段
- 如果名称不合法（不是 kebab-case），先让用户提供合法名称
- 如果同名变更已存在，建议继续那个变更，而不是重复创建
- 只有在使用非默认工作流时才传 \`--schema\`

${getModoBEndPlanningHint()}`,
    license: 'MIT',
    compatibility: '需要安装 dwsp CLI。',
    metadata: { author: 'duowenspec', version: '1.0' },
  };
}

export function getOpsxNewCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: New',
    description: '使用实验产物工作流发起新变更（OPSX）',
    category: '工作流',
    tags: ['workflow', 'artifacts', 'experimental'],
    content: `使用实验产物驱动方式发起一个新变更。

**输入**：\`/dwsp:new\` 后面的参数可以是变更名（kebab-case），也可以是用户想构建内容的描述。

**步骤**

1. **如果还没有输入内容，先问清楚要做什么**

   使用 **AskUserQuestion tool**（开放式提问，不给预设选项）询问：
   > "你想处理什么变更？请描述你想新增或修复的内容。"

   根据用户描述推导一个 kebab-case 名称（例如："新增用户认证" → \`add-user-auth\`）。

   **重要**：在没弄清用户目标前，不要继续。

2. **确定要使用的工作流 schema**

   除非用户明确要求其它工作流，否则使用默认 schema（不要传 \`--schema\`）。

   **只有在这些情况下才使用其它 schema：**
   - 用户点名某个 schema → 传入 \`--schema <name>\`
   - 用户说“看看有哪些工作流 / schema” → 运行 \`dwsp schemas --json\` 后再让用户选择

   **否则**：直接省略 \`--schema\`，走默认流程。

3. **创建变更目录**
   \`\`\`bash
   dwsp new change "<name>"
   \`\`\`
   只有当用户明确指定非默认工作流时才追加 \`--schema <name>\`。
   这会在 \`duowenspec/changes/<name>/\` 下创建带对应 schema 的变更骨架。

4. **查看产物状态**
   \`\`\`bash
   dwsp status --change "<name>"
   \`\`\`
   这会显示哪些产物还未创建，哪些产物已经就绪（依赖满足）。

5. **获取第一份产物的指令**
   第一份产物取决于 schema。先从状态输出里找到第一个状态为 "ready" 的产物。
   \`\`\`bash
   dwsp instructions <first-artifact-id> --change "<name>"
   \`\`\`
   该命令会输出创建第一份产物所需的模板与上下文。

6. **到这里先停下，等待用户下一步指示**

**输出**

完成上述步骤后，给出一段总结：
- 变更名称与所在路径
- 当前使用的 schema / 工作流，以及它的产物顺序
- 当前状态（0/N 个产物已完成）
- 第一份产物的模板
- 提示："准备好创建第一份产物了吗？运行 \`/dwsp:continue\`，或者直接告诉我这次变更主要是做什么，我就可以帮你起草。"

**约束**
- 现在不要创建任何产物，只展示指令
- 不要继续推进到第一份产物模板之后的阶段
- 如果名称不合法（不是 kebab-case），先让用户提供合法名称
- 如果同名变更已存在，建议改用 \`/dwsp:continue\`
- 只有在使用非默认工作流时才传 \`--schema\`

${getModoBEndPlanningHint()}`
  };
}
