/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

export function getOnboardSkillTemplate(): SkillTemplate {
  return {
    name: 'duowenspec-onboard',
    description: 'DuowenSpec 引导式上手流程：带讲解地走完整个工作流，并结合真实代码库操作。',
    instructions: getOnboardInstructions(),
    license: 'MIT',
    compatibility: '需要安装 dwsp CLI。',
    metadata: { author: 'duowenspec', version: '1.0' },
  };
}

function getOnboardInstructions(): string {
  return `带用户完整走一遍他们的第一轮 DuowenSpec 工作流。这是一个教学式流程：你会一边在真实代码库里做事，一边解释每一步的作用与节奏。

---

## 预检查

开始前，先确认 DuowenSpec CLI（\`dwsp\`）是否可用：

\`\`\`bash
# Unix/macOS
dwsp --version 2>&1 || echo "CLI_NOT_INSTALLED"
# Windows (PowerShell)
# if (Get-Command dwsp -ErrorAction SilentlyContinue) { dwsp --version } else { echo "CLI_NOT_INSTALLED" }
\`\`\`

**如果 CLI 未安装：**
> 当前还没有安装 DuowenSpec CLI（\`dwsp\`）。请先安装好，再回来执行 \`/dwsp:onboard\`。

如果没装好，就到这里停止。

---

## 阶段 1：欢迎与说明

向用户展示：

\`\`\`
## 欢迎使用 DuowenSpec

我会带你完整走一遍一次真实的变更流程：从一个想法开始，到实现完成，再到归档收尾。

这次你会实际经历：
1. 在代码库里挑一个真实的小任务
2. 用 explore 模式快速理解问题
3. 创建一个 change，作为这次工作的容器
4. 依次补齐 proposal → specs → design → tasks
5. 根据任务完成实现
6. 把完成的 change 归档

预计时间：约 15 到 20 分钟。

我们先从挑一个合适的小任务开始。
\`\`\`

---

## 阶段 2：选择一个真实的小任务

### 代码库扫描

先在代码库里找一些适合作为第一次演练的小切口。优先寻找：

1. **TODO / FIXME 注释**
   搜索 \`TODO\`、\`FIXME\`、\`HACK\`、\`XXX\`
2. **缺少错误处理**
   例如吞掉异常的 \`catch\`，或高风险操作未做异常保护
3. **缺少测试的函数**
   交叉查看 \`src/\` 和测试目录
4. **类型问题**
   例如 TypeScript 里的 \`: any\`、\`as any\`
5. **调试残留**
   例如 \`console.log\`、\`console.debug\`、\`debugger\`
6. **缺少输入校验**
   尤其是用户输入、接口参数、表单处理逻辑

也顺手看看近期 git 活动：

\`\`\`bash
# Unix/macOS
git log --oneline -10 2>/dev/null || echo "No git history"
# Windows (PowerShell)
# git log --oneline -10 2>$null; if ($LASTEXITCODE -ne 0) { echo "No git history" }
\`\`\`

### 给出 3 到 4 个候选项

基于扫描结果，向用户给出具体建议，例如：

\`\`\`
## 可作为首次演练的任务

**1. [最值得先做的任务]**
   位置：\`src/path/to/file.ts:42\`
   范围：约 1-2 个文件，20-30 行
   原因：[简要说明为什么适合]

**2. [第二个任务]**
   位置：\`src/another/file.ts\`
   范围：约 1 个文件，15 行
   原因：[简要说明]

**3. [第三个任务]**
   位置：[location]
   范围：[estimate]
   原因：[简要说明]

**4. 想做别的也可以**
   你也可以直接告诉我你想处理什么。

你对哪一个感兴趣？也可以直接说你自己的想法。
\`\`\`

如果没扫到明显的小切口，就直接问：
> 我没有在代码库里看到特别明显的快速切口。你最近有没有一个一直想补上、而且规模不大的小改动？

### 范围提醒

如果用户选中的事情明显过大（例如大功能、多天工作量）：

\`\`\`
这个方向当然有价值，但对第一次完整体验 DuowenSpec 来说，范围可能偏大。

如果这次目的是理解工作流，越小的任务越容易走完整个闭环，也更容易把每个产物的作用看清楚。

你可以考虑：
1. 先切小一点，只做其中最核心的一小块
2. 换一个更小、更快能闭环的任务
3. 还是做这个，我就按这个带你走，只是会更久一些

你更倾向哪一种？
\`\`\`

这是软提醒，不要和用户争。用户坚持的话，可以继续。

---

## 阶段 3：演示 explore 模式

任务确定后，先简单演示一下 explore：

\`\`\`
在正式创建 change 之前，我先带你快速体验一下 **explore 模式**。它的作用是在承诺方案之前，先把问题摸清楚。
\`\`\`

用 1 到 2 分钟看一下相关代码：
- 阅读涉及的文件
- 需要时画一个简单 ASCII 图
- 记录潜在风险、限制和注意点

然后展示类似结果：

\`\`\`
## 快速探索

[你的简短分析：发现了什么、哪些地方需要注意]

┌─────────────────────────────────────────┐
│   [如果有帮助，可以放一个 ASCII 图]     │
└─────────────────────────────────────────┘

这就是 \`/dwsp:explore\` 的典型用法：先想清楚，再动手实现。

接下来我们创建一个 change，把这次工作装进去。
\`\`\`

**暂停**：等用户确认后再继续。

---

## 阶段 4：创建 change

先解释 change 的作用：

\`\`\`
## 创建 Change

在 DuowenSpec 里，change 是一次工作的容器。它把这次工作的思考、设计、任务和最终记录都集中在一起。

它通常位于 \`duowenspec/changes/<name>/\`，里面会放 proposal、specs、design、tasks 等产物。

我现在就为这个任务创建一个。
\`\`\`

执行：

\`\`\`bash
dwsp new change "<derived-name>"
\`\`\`

然后展示结果：

\`\`\`
已创建：\`duowenspec/changes/<name>/\`

目录结构大致如下：

duowenspec/changes/<name>/
├── proposal.md    ← 说明为什么做、做什么
├── design.md      ← 说明准备怎么做
├── specs/         ← 放细化需求
└── tasks.md       ← 放实现清单

下面先写第一份产物：proposal。
\`\`\`

---

## 阶段 5：Proposal

先解释 proposal 的作用：

\`\`\`
## Proposal

proposal 负责说明这次变更为什么值得做、整体上会改什么。

你可以把它理解成一次工作的“高层说明”。
\`\`\`

先起草，不急着落盘：

\`\`\`
下面是一版 proposal 草稿：

---

## Why

[用 1-2 句话说明问题或机会]

## What Changes

[列出主要变化点]

## Capabilities

### New Capabilities
- \`<capability-name>\`：[简短说明]

### Modified Capabilities
<!-- 如果是在改已有能力，就写这里 -->

## Impact

- \`src/path/to/file.ts\`：[会改什么]
- [其他可能受影响的文件]

---

这版是否准确表达了你的意图？如果你愿意，我可以先调整一下再保存。
\`\`\`

**暂停**：等待用户确认或修改意见。

确认后，再获取 proposal 指令并写入：

\`\`\`bash
dwsp instructions proposal --change "<name>" --json
\`\`\`

将内容保存到 \`duowenspec/changes/<name>/proposal.md\`。

可以顺手补一句：
\`\`\`
Proposal 已保存。这份文档描述的是“为什么做”，后续理解变更背景时会很有用。
\`\`\`

---

## 阶段 6：Specs

解释 specs 的作用：

\`\`\`
## Specs

specs 用来精确定义“系统应该怎么表现”。它通常使用 requirement / scenario 的结构，方便验证和测试。

对于一个小任务，往往只需要 1 份 spec。
\`\`\`

创建 spec 所在目录：

\`\`\`bash
# Unix/macOS
mkdir -p duowenspec/changes/<name>/specs/<capability-name>
# Windows (PowerShell)
# New-Item -ItemType Directory -Force -Path "duowenspec/changes/<name>/specs/<capability-name>"
\`\`\`

然后起草 spec 内容：

\`\`\`
下面是一份 spec 草稿：

---

## ADDED Requirements

### Requirement: <Name>

<描述系统应该具备的能力>

#### Scenario: <Scenario name>

- **WHEN** <触发条件>
- **THEN** <预期结果>
- **AND** <补充结果，可选>

---

这种 WHEN / THEN / AND 结构，天生就适合拿来映射测试与验收条件。
\`\`\`

保存到 \`duowenspec/changes/<name>/specs/<capability>/spec.md\`。

---

## 阶段 7：Design

解释 design 的作用：

\`\`\`
## Design

design 用来回答“准备怎么做”，包括关键技术决策、方案取舍和实现路径。

小改动的 design 可以很短，不需要为了形式而写得很重。
\`\`\`

起草 design.md：

\`\`\`
下面是一版 design 草稿：

---

## Context

[简要说明当前状态]

## Goals / Non-Goals

**Goals:**
- [本次要达成什么]

**Non-Goals:**
- [明确什么不在本次范围]

## Decisions

### Decision 1: [关键决策]

[说明方案与理由]

---

对于小任务来说，这样的 design 已经足够表达关键取舍。
\`\`\`

保存到 \`duowenspec/changes/<name>/design.md\`。

---

## 阶段 8：Tasks

解释 tasks 的作用：

\`\`\`
## Tasks

接下来把工作拆成一组可以逐项完成的任务。进入 apply 阶段后，就是围绕这些勾选项推进。

任务应该清晰、可执行，并且顺序合理。
\`\`\`

起草 tasks：

\`\`\`
下面是任务清单草稿：

---

## 1. [类别或文件]

- [ ] 1.1 [具体任务]
- [ ] 1.2 [具体任务]

## 2. 验证

- [ ] 2.1 [验证步骤]

---

这些勾选项会直接成为 apply 阶段的执行单元。准备好进入实现了吗？
\`\`\`

**暂停**：等待用户确认准备进入实现。

然后保存到 \`duowenspec/changes/<name>/tasks.md\`。

---

## 阶段 9：Apply（实现）

解释 apply 的作用：

\`\`\`
## 开始实现

现在进入实现阶段。我们会按 tasks.md 一项一项推进，并在完成后打勾。

实现过程中，我会适度引用 specs 和 design，但不会把过程讲得过细。
\`\`\`

实际执行时：

1. 宣布当前任务：\"正在处理任务 N：[描述]\"
2. 在代码库里实现改动
3. 自然引用 specs / design，例如：\"spec 里要求 X，所以这里按 Y 来做\"
4. 在 tasks.md 中把 \`- [ ]\` 改成 \`- [x]\`
5. 简短汇报：\"✓ 任务 N 已完成\"

全部完成后，可展示：

\`\`\`
## 实现完成

所有任务都已完成：
- [x] 任务 1
- [x] 任务 2
- [x] ...

这个 change 已经实现完毕。最后一步，我们把它归档。
\`\`\`

---

## 阶段 10：Archive

解释 archive 的作用：

\`\`\`
## 归档

当一个 change 完成后，就把它从 \`duowenspec/changes/\` 移到 \`duowenspec/changes/archive/YYYY-MM-DD-<name>/\`。

归档后的 change 就是项目的决策记录。以后回看时，可以知道当初为什么这样做。
\`\`\`

执行：

\`\`\`bash
dwsp archive "<name>"
\`\`\`

展示结果：

\`\`\`
已归档到：\`duowenspec/changes/archive/YYYY-MM-DD-<name>/\`

代码已经保留在代码库里，这份 change 也被作为历史记录保留下来了。
\`\`\`

---

## 阶段 11：回顾与下一步

\`\`\`
## 你已经完成了一次完整的 DuowenSpec 流程

这轮你实际经历了：

1. **Explore**：先理解问题
2. **New**：创建 change 容器
3. **Proposal**：说明为什么做
4. **Specs**：精确定义要做什么
5. **Design**：说明准备怎么做
6. **Tasks**：拆成可执行步骤
7. **Apply**：逐项实现
8. **Archive**：把记录沉淀下来

这个节奏既适用于小修复，也适用于更大的功能。

---

## 常用命令参考

**核心流程：**

| 命令 | 作用 |
|------|------|
| \`/dwsp:propose\` | 创建 change 并一次生成全部产物 |
| \`/dwsp:explore\` | 在动手前或过程中梳理问题 |
| \`/dwsp:apply\` | 根据 change 中的任务推进实现 |
| \`/dwsp:archive\` | 归档已完成的 change |

**补充命令：**

| 命令 | 作用 |
|------|------|
| \`/dwsp:new\` | 新建 change，并按步骤逐个产生产物 |
| \`/dwsp:continue\` | 继续已有 change |
| \`/dwsp:ff\` | 快速推进：一次生成实现前所需产物 |
| \`/dwsp:verify\` | 检查实现是否与产物一致 |

---

## 接下来可以做什么

现在你已经掌握节奏了。接下来可以直接拿一个你真正想做的改动，用 \`/dwsp:propose\` 开始。
\`\`\`

---

## 中途退出时的处理

### 用户想暂停

如果用户表示想停一下、下次再继续，或显得不想继续当前流程：

\`\`\`
没问题。当前 change 已经保存在 \`duowenspec/changes/<name>/\`。

之后你可以这样继续：
- \`/dwsp:continue <name>\`：继续补齐产物
- \`/dwsp:apply <name>\`：如果任务已经齐了，就直接进入实现

这次工作不会丢，等你准备好再回来就行。
\`\`\`

要平稳收尾，不要给用户压力。

### 用户只想看命令，不想走教程

如果用户表示只想看命令列表，或者想跳过整个引导：

\`\`\`
## DuowenSpec 快速参考

**核心流程：**

| 命令 | 作用 |
|------|------|
| \`/dwsp:propose <name>\` | 创建 change 并生成全部产物 |
| \`/dwsp:explore\` | 思考和调查问题（不直接改代码） |
| \`/dwsp:apply <name>\` | 开始实现任务 |
| \`/dwsp:archive <name>\` | 完成后归档 |

**补充命令：**

| 命令 | 作用 |
|------|------|
| \`/dwsp:new <name>\` | 逐步创建 change |
| \`/dwsp:continue <name>\` | 继续已有 change |
| \`/dwsp:ff <name>\` | 一次生成全部实现前产物 |
| \`/dwsp:verify <name>\` | 核对实现与产物是否一致 |

如果你想直接开始，最推荐先试 \`/dwsp:propose\`。
\`\`\`

然后平稳退出。

---

## 约束

- 在关键节点遵循 **EXPLAIN → DO → SHOW → PAUSE** 节奏
- 实现阶段保持轻量说明，不要讲成大段教程
- 即使任务很小，也不要省掉关键阶段，因为这次目标是让用户看懂完整工作流
- 在标记了“暂停”的地方等用户确认，但不要过度打断节奏
- 如果用户中途退出，要平稳收尾，不要施压
- 尽量使用真实代码库里的任务，不要拿虚构示例走流程
- 可以柔和地引导用户缩小范围，但最终尊重用户选择`;
}

export function getOpsxOnboardCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Onboard',
    description: '引导式上手：带讲解走完整个 DuowenSpec 工作流',
    category: '工作流',
    tags: ['workflow', 'onboarding', 'tutorial', 'learning'],
    content: getOnboardInstructions(),
  };
}
