/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';
import { getModoBEndPlanningHint } from './shared-b-end.js';

export function getOpsxProposeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-propose',
    description: '一步生成完整变更提案。适用于用户快速描述目标并产出 proposal、design、specs、tasks。',
    instructions: `提出一个新变更：一步创建并生成全部产物。

我会创建变更并生成以下产物：
- proposal.md（做什么、为什么做）
- design.md（怎么做）
- tasks.md（实现步骤）

在这个企业优先分支中，proposal 还应明确：
- 核心用户故事（Core User Stories）
- 发布覆盖范围（Release Coverage）
- 发布证据计划（Release Evidence Plan）
- 非目标范围（Out of Scope）

准备进入实现时，运行 /dwsp:apply

---

**输入**: 用户请求应包含变更名（kebab-case），或描述想要构建/修复的内容。

**步骤**

1. **如果输入不清晰，先询问用户要做什么**

   使用 **AskUserQuestion tool**（开放式提问，无预设选项）询问：
   > "你想处理什么变更？请描述你想新建或修复的内容。"

   根据用户描述推导 kebab-case 名称（例如："新增用户认证" → \`add-user-auth\`）。

   **重要**: 在未理解用户目标前，不要继续。

2. **创建变更目录**
   \`\`\`bash
   dwsp new change "<name>"
   \`\`\`
   该命令会在 \`openspec/changes/<name>/\` 下创建脚手架，并包含 \`.openspec.yaml\`。

3. **获取产物生成顺序**
   \`\`\`bash
   dwsp status --change "<name>" --json
   \`\`\`
   解析 JSON，获取：
   - \`applyRequires\`: 实现前必须完成的产物 ID 列表（例如 \`["tasks"]\`）
   - \`artifacts\`: 全部产物及其状态、依赖关系

4. **按顺序创建产物，直到满足 apply 前置条件**

   使用 **TodoWrite tool** 跟踪产物创建进度。

   按依赖顺序循环处理产物（优先处理无未完成依赖的产物）：

   a. **针对每个处于 \`ready\` 状态的产物（依赖已满足）**：
      - 获取生成指引：
        \`\`\`bash
        dwsp instructions <artifact-id> --change "<name>" --json
        \`\`\`
      - 指引 JSON 包含：
        - \`context\`: 项目背景（给你的约束，不要写入产物）
        - \`rules\`: 产物规则（给你的约束，不要写入产物）
        - \`template\`: 产物文件结构模板
        - \`instruction\`: 当前产物类型的写作指导
        - \`outputPath\`: 产物输出路径
        - \`dependencies\`: 可用于参考的已完成产物
      - 读取已完成依赖产物作为上下文
      - 依据 \`template\` 结构创建产物文件
      - 应用 \`context\` 与 \`rules\` 作为约束，但不要把它们原文写进文件
      - 简短反馈进度："已创建 <artifact-id>"

   b. **持续处理，直到 \`applyRequires\` 全部完成**
      - 每创建一个产物后，重新执行 \`dwsp status --change "<name>" --json\`
      - 检查 \`applyRequires\` 中每个产物是否在 \`artifacts\` 中为 \`status: "done"\`
      - 全部完成后停止

   c. **如果某个产物需要用户补充信息**（上下文不明确）：
      - 使用 **AskUserQuestion tool** 追问
      - 然后继续创建

5. **展示最终状态**
   \`\`\`bash
   dwsp status --change "<name>"
   \`\`\`

**输出**

完成全部产物后，请总结：
- 变更名称与目录位置
- 已创建产物清单及简要说明
- 当前就绪状态："全部产物已创建，可进入实现。"
- 下一步提示："运行 \`/dwsp:apply\`，或直接让我开始实现任务。"

**产物创建指引**

- 每类产物都以 \`dwsp instructions\` 返回的 \`instruction\` 字段为准
- schema 定义了每个产物应包含的内容，必须遵循
- 创建新产物前，先读取依赖产物获取上下文
- 以 \`template\` 作为输出结构，并补全对应章节
- **重要**: \`context\` 与 \`rules\` 是给你的约束，不是产物正文
  - 不要把 \`<context>\`、\`<rules>\`、\`<project_context>\` 块复制进产物
  - 它们用于指导写作，不应出现在最终输出中

**约束**
- 创建实现所需的全部产物（以 schema 的 \`apply.requires\` 为准）
- 创建任一产物前都要先读依赖产物
- 如上下文存在关键缺口，先问用户；但在可判断时应优先推进
- 若同名变更已存在，先确认用户是继续该变更还是新建
- 每写完一个产物都要确认文件已实际生成，再处理下一个

${getModoBEndPlanningHint()}`,
    license: 'MIT',
    compatibility: '需要安装 dwsp CLI。',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxProposeCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Propose',
    description: '提出新变更：一步创建并生成全部产物',
    category: '工作流',
    tags: ['workflow', 'artifacts', 'experimental'],
    content: `提出一个新变更：一步创建并生成全部产物。

我会创建变更并生成以下产物：
- proposal.md（做什么、为什么做）
- design.md（怎么做）
- tasks.md（实现步骤）

在这个企业优先分支中，proposal 还应明确：
- 核心用户故事（Core User Stories）
- 发布覆盖范围（Release Coverage）
- 发布证据计划（Release Evidence Plan）
- 非目标范围（Out of Scope）

准备进入实现时，运行 /dwsp:apply

---

**输入**: \`/dwsp:propose\` 后的参数可以是变更名（kebab-case），也可以是用户要构建/修复内容的描述。

**步骤**

1. **若未提供清晰输入，先询问用户要做什么**

   使用 **AskUserQuestion tool**（开放式提问，无预设选项）询问：
   > "你想处理什么变更？请描述你想新建或修复的内容。"

   根据用户描述推导 kebab-case 名称（例如："新增用户认证" → \`add-user-auth\`）。

   **重要**: 在未理解用户目标前，不要继续。

2. **创建变更目录**
   \`\`\`bash
   dwsp new change "<name>"
   \`\`\`
   该命令会在 \`openspec/changes/<name>/\` 下创建脚手架，并包含 \`.openspec.yaml\`。

3. **获取产物生成顺序**
   \`\`\`bash
   dwsp status --change "<name>" --json
   \`\`\`
   解析 JSON，获取：
   - \`applyRequires\`: 实现前必须完成的产物 ID 列表（例如 \`["tasks"]\`）
   - \`artifacts\`: 全部产物及其状态、依赖关系

4. **按顺序创建产物，直到满足 apply 前置条件**

   使用 **TodoWrite tool** 跟踪产物创建进度。

   按依赖顺序循环处理产物（优先处理无未完成依赖的产物）：

   a. **针对每个处于 \`ready\` 状态的产物（依赖已满足）**：
      - 获取生成指引：
        \`\`\`bash
        dwsp instructions <artifact-id> --change "<name>" --json
        \`\`\`
      - 指引 JSON 包含：
        - \`context\`: 项目背景（给你的约束，不要写入产物）
        - \`rules\`: 产物规则（给你的约束，不要写入产物）
        - \`template\`: 产物文件结构模板
        - \`instruction\`: 当前产物类型的写作指导
        - \`outputPath\`: 产物输出路径
        - \`dependencies\`: 可用于参考的已完成产物
      - 读取已完成依赖产物作为上下文
      - 依据 \`template\` 结构创建产物文件
      - 应用 \`context\` 与 \`rules\` 作为约束，但不要把它们原文写进文件
      - 简短反馈进度："已创建 <artifact-id>"

   b. **持续处理，直到 \`applyRequires\` 全部完成**
      - 每创建一个产物后，重新执行 \`dwsp status --change "<name>" --json\`
      - 检查 \`applyRequires\` 中每个产物是否在 \`artifacts\` 中为 \`status: "done"\`
      - 全部完成后停止

   c. **如果某个产物需要用户补充信息**（上下文不明确）：
      - 使用 **AskUserQuestion tool** 追问
      - 然后继续创建

5. **展示最终状态**
   \`\`\`bash
   dwsp status --change "<name>"
   \`\`\`

**输出**

完成全部产物后，请总结：
- 变更名称与目录位置
- 已创建产物清单及简要说明
- 当前就绪状态："全部产物已创建，可进入实现。"
- 下一步提示："运行 \`/dwsp:apply\` 开始实现。"

**产物创建指引**

- 每类产物都以 \`dwsp instructions\` 返回的 \`instruction\` 字段为准
- schema 定义了每个产物应包含的内容，必须遵循
- 创建新产物前，先读取依赖产物获取上下文
- 以 \`template\` 作为输出结构，并补全对应章节
- **重要**: \`context\` 与 \`rules\` 是给你的约束，不是产物正文
  - 不要把 \`<context>\`、\`<rules>\`、\`<project_context>\` 块复制进产物
  - 它们用于指导写作，不应出现在最终输出中

**约束**
- 创建实现所需的全部产物（以 schema 的 \`apply.requires\` 为准）
- 创建任一产物前都要先读依赖产物
- 如上下文存在关键缺口，先问用户；但在可判断时应优先推进
- 若同名变更已存在，先确认用户是继续该变更还是新建
- 每写完一个产物都要确认文件已实际生成，再处理下一个

${getModoBEndPlanningHint()}`
  };
}
